server:
  port: 8081

spring:
  application:
    name: service-employee
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?serverTimezone=GMT%2b8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  redis:
    port: 6379
    host: localhost
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_empty
    time-zone: Asia/Shanghai

mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:log4j2.yml
  level:
    feign: debug

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: localhost # 主机名，不配置的时候将根据操作系统的主机名来获取
  client:
    register-with-eureka: false # 是否将自己注册到注册中心，默认为 true
    fetch-registry: false # 是否从注册中心获取服务注册信息，默认为 true
    service-url: # 注册中心对外暴露的注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

feign:
  client:
    config:
      default: # 全局设置
        connectTimeout: 5000 # 毫秒
        readTimeout: 5000 # 毫秒


rocketmq:
  name-server: localhost:9876
  producer:
    group: producer-group
    retry-times-when-send-failed: 2 # 同步发送重试次数
    retry-times-when-send-async-failed: 0 # 异步发送重试次数
    send-message-timeout: 3000 # ms
    max-message-size: 4096 # byte
    compress-message-body-threshold: 1024
    retry-next-server: false # retry another broker on sending failure internally
  consumer:
    group: consumer-group