spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?serverTimezone=GMT%2b8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  redis:
    port: 6379
    host: localhost
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_empty
    time-zone: Asia/Shanghai

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  # config-location: classpath:mybatis-config.xml

