server:
  port: 8082

spring:
  application:
    name: service-attendance
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?serverTimezone=GMT%2b8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  redis:
    port: 6379
    host: localhost
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_empty
    time-zone: Asia/Shanghai

mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:log4j2.yml
  level:
    # feign 日志以什么级别监控哪个接口
    com.example.employee.client.EmployeeFeignClient: debug

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: localhost # 主机名，不配置的时候将根据操作系统的主机名来获取
  client:
    register-with-eureka: false # 是否将自己注册到注册中心，默认为 true
    fetch-registry: false # 是否从注册中心获取服务注册信息，默认为 true
    service-url: # 注册中心对外暴露的注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/